title: Marco Carbone
logo: /assets/img/marcopic.jpg
email: carbonem [at] itu.dk
description: Welcome to my webpage or whather...
twitter_username: carbonem
github_username:  carbonem

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one